export const fabricDefaultTemplates: Record<string, any> = {
  quote: {
    version: "6.0.0",
    objects: [
      // Header
      {
        type: "textbox",
        left: 50,
        top: 50,
        width: 300,
        height: 40,
        text: "QUOTATION",
        fontSize: 32,
        fontWeight: "bold",
        fill: "hsl(222.2, 47.4%, 11.2%)",
        fontFamily: "Inter",
      },
      // Company Info
      {
        type: "textbox",
        left: 50,
        top: 110,
        width: 250,
        text: "{{company.name}}",
        fontSize: 14,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        backgroundColor: "hsl(210, 40%, 96.1%, 0.3)",
        customType: "dataField",
        fieldName: "company.name",
      },
      {
        type: "textbox",
        left: 50,
        top: 140,
        width: 250,
        text: "{{company.address}}",
        fontSize: 12,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        customType: "dataField",
        fieldName: "company.address",
      },
      // Document Info (Right side)
      {
        type: "textbox",
        left: 350,
        top: 110,
        width: 195,
        text: "Quote #: {{document.number}}",
        fontSize: 12,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        textAlign: "right",
        customType: "dataField",
        fieldName: "document.number",
      },
      {
        type: "textbox",
        left: 350,
        top: 135,
        width: 195,
        text: "Date: {{document.date}}",
        fontSize: 12,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        textAlign: "right",
        customType: "dataField",
        fieldName: "document.date",
      },
      {
        type: "textbox",
        left: 350,
        top: 160,
        width: 195,
        text: "Valid Until: {{quote.valid_until}}",
        fontSize: 12,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        textAlign: "right",
        customType: "dataField",
        fieldName: "quote.valid_until",
      },
      // Customer Section
      {
        type: "textbox",
        left: 50,
        top: 200,
        width: 200,
        text: "Bill To:",
        fontSize: 14,
        fontWeight: "bold",
        fill: "hsl(222.2, 47.4%, 11.2%)",
      },
      {
        type: "textbox",
        left: 50,
        top: 230,
        width: 250,
        text: "{{customer.name}}",
        fontSize: 12,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        customType: "dataField",
        fieldName: "customer.name",
      },
      // Totals (Bottom)
      {
        type: "textbox",
        left: 350,
        top: 720,
        width: 195,
        text: "Subtotal: {{quote.subtotal}}",
        fontSize: 14,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        textAlign: "right",
      },
      {
        type: "textbox",
        left: 350,
        top: 750,
        width: 195,
        text: "Tax: {{quote.tax}}",
        fontSize: 14,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        textAlign: "right",
      },
      {
        type: "textbox",
        left: 350,
        top: 780,
        width: 195,
        text: "Total: {{quote.total}}",
        fontSize: 16,
        fontWeight: "bold",
        fontFamily: "monospace",
        fill: "hsl(222.2, 47.4%, 11.2%)",
        textAlign: "right",
      },
    ],
  },
  invoice: {
    version: "6.0.0",
    objects: [
      {
        type: "textbox",
        left: 50,
        top: 50,
        width: 300,
        text: "INVOICE",
        fontSize: 32,
        fontWeight: "bold",
        fill: "hsl(222.2, 47.4%, 11.2%)",
      },
      {
        type: "textbox",
        left: 50,
        top: 110,
        width: 250,
        text: "{{company.name}}",
        fontSize: 14,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        customType: "dataField",
        fieldName: "company.name",
      },
      {
        type: "textbox",
        left: 350,
        top: 110,
        width: 195,
        text: "Invoice #: {{document.number}}",
        fontSize: 12,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        textAlign: "right",
        customType: "dataField",
      },
      {
        type: "textbox",
        left: 350,
        top: 135,
        width: 195,
        text: "Due Date: {{invoice.due_date}}",
        fontSize: 12,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        textAlign: "right",
        customType: "dataField",
        fieldName: "invoice.due_date",
      },
    ],
  },
  purchase_order: {
    version: "6.0.0",
    objects: [
      {
        type: "textbox",
        left: 50,
        top: 50,
        width: 300,
        text: "PURCHASE ORDER",
        fontSize: 28,
        fontWeight: "bold",
        fill: "hsl(222.2, 47.4%, 11.2%)",
      },
      {
        type: "textbox",
        left: 50,
        top: 110,
        width: 250,
        text: "{{company.name}}",
        fontSize: 14,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        customType: "dataField",
        fieldName: "company.name",
      },
      {
        type: "textbox",
        left: 350,
        top: 110,
        width: 195,
        text: "PO #: {{document.number}}",
        fontSize: 12,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        textAlign: "right",
        customType: "dataField",
      },
    ],
  },
  field_report: {
    version: "6.0.0",
    objects: [
      {
        type: "textbox",
        left: 50,
        top: 50,
        width: 300,
        text: "FIELD REPORT",
        fontSize: 28,
        fontWeight: "bold",
        fill: "hsl(222.2, 47.4%, 11.2%)",
      },
      {
        type: "textbox",
        left: 50,
        top: 110,
        width: 250,
        text: "Site: {{report.site}}",
        fontSize: 14,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        customType: "dataField",
        fieldName: "report.site",
      },
      {
        type: "textbox",
        left: 50,
        top: 140,
        width: 250,
        text: "Technician: {{report.technician}}",
        fontSize: 14,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        customType: "dataField",
        fieldName: "report.technician",
      },
      {
        type: "textbox",
        left: 350,
        top: 110,
        width: 195,
        text: "Date: {{document.date}}",
        fontSize: 12,
        fontFamily: "monospace",
        fill: "hsl(215.4, 16.3%, 46.9%)",
        textAlign: "right",
        customType: "dataField",
      },
    ],
  },
};
